import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';

const ROOT = process.cwd();
const BRAND = `${ROOT}/apps/web/public/brand`;
// A real lair, generated by the engine — see tools/README for how to swap it.
const lair = JSON.parse(readFileSync(`${ROOT}/tools/lair-d6.json`, 'utf8'));

const inner = (key) =>
  readFileSync(`${BRAND}/dragonjob-${key}.svg`, 'utf8')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .trim();

const page = (key) => `<style>
*{margin:0;padding:0;box-sizing:border-box}
html,body{width:1500px;height:500px;overflow:hidden;background:#050a07}
#bg{position:absolute;inset:0;width:1500px;height:500px;display:block}
#veil{position:absolute;inset:0;
  background:
    radial-gradient(42% 130% at 33% 52%, rgba(255,215,94,.17), transparent 72%),
    linear-gradient(180deg, rgba(5,10,7,.5), rgba(5,10,7,.06) 32%, rgba(5,10,7,.1) 64%, rgba(5,10,7,.72)),
    radial-gradient(125% 155% at 50% 50%, rgba(5,10,7,.12) 0%, rgba(5,10,7,.7) 70%, rgba(5,10,7,.94) 100%);
}
#lock{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;gap:44px;
  font-family:ui-monospace,"SF Mono",Menlo,Consolas,monospace}
#lock svg{width:244px;height:244px;flex:0 0 auto;
  filter:drop-shadow(0 14px 40px rgba(0,0,0,.72)) drop-shadow(0 0 26px rgba(255,215,94,.16))}
.txt{display:flex;flex-direction:column;gap:0}
h1{font-size:68px;font-weight:700;line-height:.99;letter-spacing:.115em;color:#f6ead0;
  text-shadow:0 3px 22px rgba(0,0,0,.85)}
.rule{height:1px;width:100%;margin:20px 0 15px;
  background:linear-gradient(90deg,#c08f2c,rgba(192,143,44,.12))}
.tag{font-size:19px;letter-spacing:.235em;color:#8fb3a1;text-transform:uppercase;
  text-shadow:0 2px 12px rgba(0,0,0,.8)}
.dom{font-size:16px;letter-spacing:.3em;color:#ffd75e;margin-top:20px;text-transform:lowercase;
  text-shadow:0 2px 12px rgba(0,0,0,.8)}
</style>
<canvas id="bg" width="1500" height="500"></canvas>
<div id="veil"></div>
<div id="lock">
  <svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">${inner(key)}</svg>
  <div class="txt">
    <h1>THE<br/>DRAGON JOB</h1>
    <div class="rule"></div>
    <div class="tag">One lair · one crew · one shot a day</div>
    <div class="dom">thedragonjob.com</div>
  </div>
</div>
<script>
(() => {
const LAIR = ${JSON.stringify(lair)};
const T = 24, ROCK = 0;
// the same tile pass the game's renderer runs — same hash, same colours
const sr = (v) => Math.abs(Math.sin(v) * 43758.5453) % 1;
const off = document.createElement('canvas');
off.width = LAIR.cols * T; off.height = LAIR.rows * T;
const g = off.getContext('2d');
g.imageSmoothingEnabled = false;
const gi = (x, y) => y * LAIR.cols + x;
const inb = (x, y) => x >= 0 && y >= 0 && x < LAIR.cols && y < LAIR.rows;
for (let y = 0; y < LAIR.rows; y++) for (let x = 0; x < LAIR.cols; x++) {
  const c = LAIR.grid[gi(x, y)], px = x * T, py = y * T, sd = x * 7.13 + y * 3.7;
  if (c === ROCK) {
    g.fillStyle = sr(sd) > 0.5 ? '#16291f' : '#122219'; g.fillRect(px, py, T, T);
    g.fillStyle = '#0b1710'; g.fillRect(px, py + T - 3, T, 3);
    g.fillStyle = '#234a34'; g.fillRect(px, py, T, 2);
  } else {
    g.fillStyle = '#101a12'; g.fillRect(px, py, T, T);
    if ((x + y) % 2) { g.fillStyle = 'rgba(0,0,0,.16)'; g.fillRect(px, py, T, T); }
    if (sr(sd * 7) > 0.82) { g.fillStyle = '#2ab070'; g.fillRect(px + (sr(sd * 6) * 20 | 0), py + (sr(sd * 8) * 20 | 0), 2, 2); }
    const edge = (dx, dy) => inb(x + dx, y + dy) && LAIR.grid[gi(x + dx, y + dy)] === ROCK;
    g.fillStyle = '#2c5a40';
    if (edge(0, -1)) g.fillRect(px, py, T, 2);
    if (edge(0, 1)) g.fillRect(px, py + T - 2, T, 2);
    if (edge(-1, 0)) g.fillRect(px, py, 2, T);
    if (edge(1, 0)) g.fillRect(px + T - 2, py, 2, T);
  }
}
// the hoard, glowing through the dark
g.globalCompositeOperation = 'lighter';
for (const { x, y, r, a } of [
  ...LAIR.piles.map((p) => ({ ...p, r: 58, a: 0.72 })),
  ...LAIR.chests.map((c) => ({ ...c, r: 44, a: 0.5 })),
]) {
  const cx = x * T + T / 2, cy = y * T + T / 2;
  const rg = g.createRadialGradient(cx, cy, 0, cx, cy, r);
  rg.addColorStop(0, \`rgba(255,215,94,\${a})\`);
  rg.addColorStop(1, 'rgba(255,215,94,0)');
  g.fillStyle = rg; g.beginPath(); g.arc(cx, cy, r, 0, 7); g.fill();
}
g.globalCompositeOperation = 'source-over';

const cv = document.getElementById('bg');
const c2 = cv.getContext('2d');
c2.imageSmoothingEnabled = false;
const s = Math.max(1500 / off.width, 500 / off.height);
c2.drawImage(off, (1500 - off.width * s) / 2, (500 - off.height * s) / 2 - 40, off.width * s, off.height * s);
document.title = 'ready';
})();
</script>`;

const b = await chromium.launch({ ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}), args: ['--no-sandbox'] });
for (const key of ['seal', 'signet', 'eclipse']) {
  const p = await b.newPage({ viewport: { width: 1500, height: 500 } });
  p.on('pageerror', (e) => console.log('ERR', key, String(e)));
  await p.setContent(page(key));
  await p.waitForTimeout(400);
  await p.screenshot({ path: `${BRAND}/dragonjob-x-header-${key}-1500x500.png` });
  await p.close();
  console.log('header', key);
}
await b.close();
